CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL, 
    ADRESS TEXT, 
    PHONE TEXT, 
    AGE INTEGER
    );
INSERT INTO STUDENT (ROLL_NO, NAME, ADRESS, PHONE, AGE) VALUES
('1', 'Ram', 'Delhi', '980000001', 18),
('2', 'Shyam', 'Lalitpur', '980000002', 21),
('3', 'Hari', 'Bhaktapur', '980000003', 22),
('4', 'Sita', 'Pokhara', '980000004', 20),
('5', 'Gita', 'Biratnagar', '980000005', 23);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADRESS = 'Delhi';
SELECT * FROM STUDENT WHERE NAME = 'Ram' AND AGE = 18;
SELECT * FROM STUDENT WHERE NAME = 'Ram' OR NAME = 'Sujit';
SELECT * FROM STUDENT WHERE NAME = 'Ram' OR AGE = 20;
SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'Ram' OR NAME = 'Ramesh');
